<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>GestionClientes.Entidades</RootNamespace>
    <AssemblyName>GestionClientes.Entidades</AssemblyName>
    <OptionStrict>On</OptionStrict>
    <OptionExplicit>On</OptionExplicit>
    <OptionInfer>On</OptionInfer>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Company>Kamilo Martínez</Company>
    <Product>Sistema de Gestion de Clientes</Product>
  </PropertyGroup>

</Project>
